default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: postgres

development:
  <<: *default
  database: test_api_development
  adapter: postgresql
  pool: 5
  username: postgres
  password: 'postgres'
  host: localhost

test:
  <<: *default
  database: test_api_test
  adapter: postgresql
  pool: 5
  username: postgres
  password: 'postgres'
  host: localhost
  

production:
  <<: *default
  database: a2_o1d6
  username: a3
  password: <%= ENV["TEST_API_PRODUCTION_DATABASE_PASSWORD"] %>

