default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_development") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "myapp_user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_test") %>
  username: <%= ENV.fetch("DATABASE_USERNAME", "myapp_user") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

